name: "Upload SARIF"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest #ubuntu --- con PVS-Studio installato
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Compile
      run: |
        wget -q -O - https://cdn.pvs-studio.com/etc/pubkey.txt | apt-key add -

        wget -O /etc/apt/sources.list.d/viva64.list https://cdn.pvs-studio.com/etc/viva64.list

        apt-get update
        apt-get install pvs-studio
        
        touch makefile
        echo "file.o: f.c" > makefile
        echo -e "\tgcc -c -Wall -Wextra -Wpedantic f.c" >> makefile
        pvs-studio-analyzer trace -- make -j8
        pvs-studio-analyzer analyze -j8 -l PVS-Studio.lic -o PVS-Studio.log
        plog-converter PVS-Studio.log -t sarif -o results.sarif
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artefatti
        path: results.sarif
      
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
